source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'Tutorial' do
  pod 'Presentation', path: '../../'
  pod 'Hue', git: 'https://github.com/hyperoslo/Hue', branch: 'swift3'
end
