source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'Tutorial' do
    pod 'Presentation', path: '../../'
    pod 'Hex', '~> 2.0'
    pod 'Pages', git: 'https://github.com/hyperoslo/Pages'
end
