source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

pod 'Presentation', path: '../'
pod 'Pages', git: 'https://github.com/hyperoslo/Pages.git'
pod 'Hex'
pod 'Cartography'

target 'Tests' do
    use_frameworks!
    pod 'Quick'
    pod 'Nimble'
end
