use_frameworks!

platform :ios, '8.0'

pod 'Presentation', path: '../../'
pod 'Cartography', git: 'https://github.com/robb/Cartography.git'
pod 'Pages', git: 'https://github.com/hyperoslo/Pages'

pod 'Hex', '~> 2.0'
